# -*- coding: utf-8 -*-
"""DBOZero deterministic resource builder.

This is the canonical ``dboc build`` backend. It reads the active translation
queue, transforms the requested language variant, writes from a pristine
source tree, and runs deterministic resource validation.

The builder never starts the game and never modifies the source snapshot.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import shutil
import tempfile
from pathlib import Path

from hanhua_v3.runtime.auto_translate_v2 import normalize_taiwan
from hanhua_v3.runtime.build_progress import Progress
from hanhua_v3.runtime.resource_validator import ValidationError, validate_build
from hanhua_v3.runtime.resource_writer import QueueRow, WriteError, read_queue, write_queue

ROOT = Path(__file__).resolve().parent
DEFAULT_QUEUE = ROOT / "data" / "new_translations.tsv"
OUTPUT_DIRS = {
    "simplified": ROOT / "output" / "DBOZero",
    "mainland": ROOT / "output" / "DBOZero",
    "taiwan": ROOT / "output_taiwan" / "DBOZero",
}


class BuildError(RuntimeError):
    """Raised when a build cannot be produced safely."""


def _variant_name(value: str) -> str:
    value = value.strip().lower()
    if value == "mainland":
        return "simplified"
    if value not in {"simplified", "taiwan"}:
        raise BuildError(f"Unsupported build variant: {value}")
    return value


def _resolve_source_root(source_dir: Path) -> Path:
    root = source_dir.expanduser().resolve()
    if (root / "DBOZero").is_dir():
        root = root / "DBOZero"
    if not root.is_dir():
        raise BuildError(f"Source root not found: {root}")
    if not (root / "pack").is_dir():
        raise BuildError(f"Source root does not contain pack/: {root}")
    return root


def _safe_output_root(path: Path) -> Path:
    root = path.expanduser().resolve()
    allowed = {(ROOT / "output").resolve(), (ROOT / "output_taiwan").resolve()}
    if not any(root == base / "DBOZero" for base in allowed):
        raise BuildError(
            "Refusing unsafe output path. Builder outputs must be "
            "./output/DBOZero or ./output_taiwan/DBOZero."
        )
    return root


def _prepare_output(root: Path, force: bool) -> None:
    if root.exists():
        if not force:
            raise BuildError(f"Output already exists: {root}. Use --force to replace it.")
        if root.is_file():
            raise BuildError(f"Output path is a file: {root}")
        shutil.rmtree(root)
    root.mkdir(parents=True, exist_ok=True)


def _variant_rows(rows: list[QueueRow], variant: str) -> list[QueueRow]:
    if variant == "simplified":
        return rows
    return [
        QueueRow(
            file=row.file,
            locator=row.locator,
            source=row.source,
            translation=normalize_taiwan(row.translation),
            encoding=row.encoding,
            kind=row.kind,
        )
        for row in rows
    ]


def _write_temp_queue(rows: list[QueueRow]) -> Path:
    handle = tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8-sig",
        newline="",
        prefix="dbozero-build-",
        suffix=".tsv",
        delete=False,
    )
    path = Path(handle.name)
    try:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(
            [
                "surface",
                "file",
                "id",
                "source_hash",
                "source_text",
                "zh_cn",
                "status",
                "kind",
                "encoding",
                "legacy_source",
                "legacy_row",
                "note",
            ]
        )
        for row in rows:
            writer.writerow(
                [
                    "",
                    row.file,
                    row.locator,
                    hashlib.sha256(row.source.encode("utf-8")).hexdigest(),
                    row.source,
                    row.translation,
                    "translated",
                    row.kind,
                    row.encoding,
                    "",
                    "",
                    "generated by build_output.py",
                ]
            )
    finally:
        handle.close()
    return path


def build_one(
    *,
    source_dir: Path,
    variant: str,
    queue_path: Path = DEFAULT_QUEUE,
    output_dir: Path | None = None,
    force: bool = False,
    no_parallel: bool = False,
) -> int:
    # Sequential writing is intentional for the deterministic baseline.
    # The flag remains accepted for CLI compatibility and future parallel work.
    del no_parallel
    variant = _variant_name(variant)
    source_root = _resolve_source_root(source_dir)
    output_root = _safe_output_root(output_dir or OUTPUT_DIRS[variant])
    if source_root == output_root or source_root in output_root.parents or output_root in source_root.parents:
        raise BuildError("Source and output roots must be separate")
    if not queue_path.is_file():
        raise BuildError(f"Translation queue not found: {queue_path}")

    try:
        rows = read_queue(queue_path)
    except WriteError as exc:
        raise BuildError(str(exc)) from exc
    variant_rows = _variant_rows(rows, variant)
    stage_size = max(len(variant_rows), 1)
    progress = Progress(1 + stage_size * 3)
    temp_queue: Path | None = None

    try:
        progress.begin_stage("檢查來源", 1)
        required = [
            source_root / "pack" / name
            for name in ("lang0.pak", "tbl0.pak", "tbl1.pak", "tbl2.pak")
        ]
        for path in required:
            if not path.is_file():
                raise BuildError(f"Missing required resource: {path}")
        progress.step()
        progress.end_stage()

        progress.begin_stage("讀取翻譯表", stage_size)
        progress.step(stage_size)
        progress.end_stage()
        print(f"  翻譯佇列：{len(rows)} 筆可寫入項目")

        temp_queue = _write_temp_queue(variant_rows)
        _prepare_output(output_root, force)

        progress.begin_stage("寫入資源", stage_size)
        try:
            stats = write_queue(temp_queue, source_root, output_root)
        except WriteError as exc:
            raise BuildError(str(exc)) from exc
        progress.step(stage_size)
        progress.end_stage()
        print(f"  有翻譯變更的資源檔案：{len(stats)}")

        progress.begin_stage("驗證輸出", stage_size)
        try:
            summary = validate_build(source_root, output_root, variant_rows)
        except ValidationError as exc:
            raise BuildError(str(exc)) from exc
        progress.step(stage_size)
        progress.end_stage()
        print(
            "  驗證："
            f" files={summary.files}, queued={summary.queued_rows}, "
            f"validated={summary.validated_rows}, untouched={summary.untouched_files}"
        )

        progress.done(f"{variant} 建置完成")
        return 0
    finally:
        if temp_queue is not None:
            try:
                temp_queue.unlink(missing_ok=True)
            except OSError:
                pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="DBOZero deterministic resource builder")
    parser.add_argument("--source-dir", type=Path, default=ROOT / "src_file" / "DBOZero")
    parser.add_argument("--variant", choices=("simplified", "mainland", "taiwan"), default="taiwan")
    parser.add_argument("--queue", type=Path, default=DEFAULT_QUEUE)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--no-parallel", action="store_true")
    args = parser.parse_args(argv)
    try:
        return build_one(
            source_dir=args.source_dir,
            variant=args.variant,
            queue_path=args.queue,
            output_dir=args.output_dir,
            force=args.force,
            no_parallel=args.no_parallel,
        )
    except BuildError as exc:
        print(f"[BUILD FAILED] {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
