"""Curated exact translations for current and recurring game terminology."""

__all__ = ["CURATED_TRANSLATIONS"]

CURATED_TRANSLATIONS = {
    # July 2026 dungeon queue and item ascension UI.
    "Dungeon Queue Ready": "副本匹配就绪",
    '[align=\\"center\\"]Party complete! Confirm to enter the dungeon.[br]Everyone must accept.': '[align=\\"center\\"]队伍已集结！请确认进入副本。[br]所有人都必须接受。',
    "Dungeons": "副本",
    "Daily": "每日",
    "Weekly": "每周",
    "Ultimate": "终极副本",
    "Join Queue": "加入匹配",
    "Enter with my party only (or solo)": "仅与当前队伍进入（或单人进入）",
    "Check registration to join the queue.": "勾选登记以加入匹配队列。",
    "Queue: %u / %u players": "队列：%u/%u人",
    "Queue: %u / %u players - waiting for more sign-ups.": "匹配队列：%u / %u 名玩家 - 等待更多玩家加入。",
    "Waiting for other players to confirm.": "等待其他玩家确认。",
    "Daily tab reserved for daily dungeon schedule.": "每日页签预留给每日副本日程。",
    "Weekly tab reserved for future dungeons.": "每周页签预留给后续副本。",
    "Upcoming World Bosses:": "即将出现的世界首领：",
    "CCBD coming soon.": "CCBD 即将开放。",
    "Ticket -": "门票 -",
    "Franium -": "弗拉尼姆-",
    "Required Level: %u": "要求等级：%u",
    "Difficulty: %s": "难度：%s",
    "Ultimate DG Grp %u": "终极副本组 %u",
    "World Supreme Boss": "世界至尊首领",
    "World Boss V2": "世界首领 V2",
    "Invasion Event": "入侵活动",
    "ZERO Event": "ZERO 活动",
    "Angel": "天使",
    "Grand Priest": "大神官",
    "Zen'oh": "全王",
    "Ascend System": "装备升阶",
    "Place an equipment piece here to ascend it to the next rarity tier.": "将一件装备放在这里，使其升阶至下一稀有度。",
    "Required Materials": "所需材料",
    "ASCEND": "升阶",
    "Ascension succeeded!": "升阶成功！",
    "Ascension failed. Success rate increased.": "升阶失败，成功率已提升。",
    "This item is already at the maximum rarity.": "该装备已达到最高稀有度。",
    '[align = "center"][font size = "12" color="f4d762"]Confirm Ascension[/font][br][br][font size = "10" color="ffffff"]Attempt to ascend this item now?[/font][br][br][font size = "10" color="f36a7c"]On failure, only the materials and zenny[br]will be lost - the item itself is kept[br]and your next success rate will increase.[/font][br][br][font size = "10" color="269eff"]Current success rate: %s%%[/font]': '[align = "center"][font size = "12" color="f4d762"]确认升阶[/font][br][br][font size = "10" color="ffffff"]现在尝试升阶该装备吗？[/font][br][br][font size = "10" color="f36a7c"]失败时只会消耗材料和索尼，[br]装备本身会保留，[br]下次升阶成功率也会提高。[/font][br][br][font size = "10" color="269eff"]当前成功率：%s%%[/font]',
    "This item cannot be ascended (no recipe found).": "该装备无法升阶（未找到配方）。",
    "You do not have the required materials.": "所需材料不足。",
    "You do not have enough zeni.": "索尼不足。",
    "This item cannot be ascended right now.": "该装备当前无法升阶。",

    # Transformations and class variants.
    "Dragon Clan Transformation": "那美克龙族变身",
    "SSJ GOD Spiritualist": "超级赛亚人之神气功师",
    "SSJ2 Spiritualist": "超级赛亚人2气功师",
    "SSJ4 Spiritualist": "超级赛亚人4气功师",
    "Ozaru Spiritualist": "大猿气功师",
    "Gotenks Buu Might": "悟天克斯布欧大魔人",
    "Gotenks Buu Wonder": "悟天克斯布欧意魔人",
    "Dark Namek Warrior": "暗黑那美克战士",
    "Dark Namek Dragon Clan": "暗黑那美克龙族",
    "SSJ Blue Spiritualist": "超级赛亚人蓝色气功师",
    "SS3 Might": "超级赛亚人3大魔人",
    "SS3 Wonder": "超级赛亚人3意魔人",
    "Orange Muscle Dragon Clan": "橙色肌肉那美克龙族",
    "Daima SS4 Spiritualist": "大魔版超级赛亚人4气功师",
    "Imperator Namek Warrior": "帝王那美克战士",
    "Imperator Namek Dragon Clan": "帝王那美克龙族",
    "Xeno Majin Might": "异时空大魔人",
    "Xeno Majin Wonder": "异时空意魔人",
    "SSJ3 Spiritualist": "超级赛亚人3气功师",
    "Golden Ozaru": "黄金大猿",
    "Golden Ozaru Spiritualist": "黄金大猿气功师",
    "White Namek Warrior": "白色那美克战士",
    "White Namek Dragon Clan": "白色那美克龙族",
    "Daima Majin Might": "大魔版大魔人",
    "Daima Majin Wonder": "大魔版意魔人",

    # Equipment, costumes, recipes, and transformation items.
    "Neptune Dogi.": "海王星道服",
    "Heroic Treasure Chest A": "英雄宝箱A",
    "Shooting Star Scroll L": "流星卷轴L",
    "Dried Hope Dragon Staff": "枯萎希望龙杖",
    "Never Melt Ice": "永不融化的冰",
    "Material Arts Capsule Lv1": "武道胶囊Lv1",
    "Material Arts Capsule Lv2": "武道胶囊Lv2",
    "Material Arts Capsule Lv3": "武道胶囊Lv3",
    "Material Arts Capsule Lv4": "武道胶囊Lv4",
    "Human Hair-08": "人类发型-08",
    "Designed By: Kunay & Ryo": "设计：Kunay与Ryo",
    "Designed By: Kunay & Ryo.": "设计：Kunay与Ryo。",
    "Bardock Heroes Outfit": "巴达克英雄套装",
    "Made By: Kunay & Ryo.": "制作：Kunay与Ryo。",
    "Whitebeard's Hat": "白胡子的帽子",
    "Vegeta Super Brolly Outfit": "贝吉塔超级布罗利套装",
    "Shadow Large Crystal": "暗影大水晶",
    "Shadow Sovereign Fan Recipe": "暗影暴君扇配方",
    "(Wonder Majin)Xeno Majin": "(意魔人)异时空魔人",
    "(Martial) Potion Super Saiyan GOD": "(武道家)超级赛亚人之神药水",
    "(Spiritualist) (7 days) Super Saiyan 2": "(气功师)(7天)超级赛亚人2",
    "(Spiritualist) (7 days) Super Saiyan Legendary Super": "(气功师)(7天)传说超级赛亚人(超)",
    "(Martial)Daima Super Saiyan 4": "(武道家)大魔版超级赛亚人4",
    "(Spiritualist)Daima Super Saiyan 4": "(气功师)大魔版超级赛亚人4",
    "(Warrior)White Namek": "(那美克战士)白色那美克",
    "(Spiritualist)White Namek": "(那美克龙族)白色那美克",
    "(Might Majin)SaibaMajin Fusion": "(大魔人)栽培魔人融合",
    "(Wonder Majin)SaibaMajin Fusion": "(意魔人)栽培魔人融合",
    "WC Daima Capsule": "WC大魔胶囊",
    "BID Makai Orb": "BID魔界宝珠",
    "Orb from Daima BID.": "来自大魔BID的宝珠。",
    "10KK Luck Coupon": "1000万幸运券",

    # Wings and their descriptions.
    "Black Makai Wings": "黑色魔界翅膀",
    "Blue Angel Wing": "蓝色天使翅膀",
    "Blue Angel Wings": "蓝色天使翅膀",
    "Mech Green Wing": "绿色机械翅膀",
    "Mech Red Wing": "红色机械翅膀",
    "Mech Pink Wing": "粉色机械翅膀",
    "Mech Blue Wing": "蓝色机械翅膀",
    "Mech Dark Wing": "暗黑机械翅膀",
    "Mech Green Wings": "绿色机械翅膀",
    "Mech Red Wings": "红色机械翅膀",
    "Mech Pink Wings": "粉色机械翅膀",
    "Mech Blue Wings": "蓝色机械翅膀",
    "Mech Dark Wings": "暗黑机械翅膀",
    "Fire Coating Wing": "火焰覆层翅膀",
    "Fire Coating Wings": "火焰覆层翅膀",
    "Owl Red Wing": "红色猫头鹰翅膀",
    "Owl Green Wing": "绿色猫头鹰翅膀",
    "Owl Yellow Wing": "黄色猫头鹰翅膀",
    "Owl Blue Wing": "蓝色猫头鹰翅膀",
    "Owl Purple Wing": "紫色猫头鹰翅膀",
    "Owl Red Wings": "红色猫头鹰翅膀",
    "Owl Green Wings": "绿色猫头鹰翅膀",
    "Owl Yellow Wings": "黄色猫头鹰翅膀",
    "Owl Blue Wings": "蓝色猫头鹰翅膀",
    "Owl Purple Wings": "紫色猫头鹰翅膀",
    "Luminous Yellow Wings": "黄色光辉翅膀",
    "Luminous Purple Wings": "紫色光辉翅膀",
    "Luminous Green Wings": "绿色光辉翅膀",
    "Luminous Fire Coating Wings": "光辉火焰覆层翅膀",
    "Luminous Dark Wings": "暗黑光辉翅膀",
    "Luminous Blue Wings": "蓝色光辉翅膀",
    "Fire Mech Wings": "火焰机械翅膀",
    "Amethyst Mech Wings": "紫晶机械翅膀",
    "Sky Mech Wings": "天空机械翅膀",
    "Nature Mech Wings": "自然机械翅膀",
    "Dark Mech Wings": "暗黑机械翅膀",
    "Celestial Wings": "天界翅膀",
    "Corrupted Double Wings": "腐化双翼",
    "Grey Small Wings": "灰色小型翅膀",
    "Red Small Wings": "红色小型翅膀",
    "Green Small Wings": "绿色小型翅膀",
    "Golden Small Wings": "金色小型翅膀",
    "Blue Small Wings": "蓝色小型翅膀",
    "Dark Small Wings": "暗黑小型翅膀",
    "Red Hail Wings": "红色冰晶翅膀",
    "Green Hail Wings": "绿色冰晶翅膀",
    "Yellow Hail Wings": "黄色冰晶翅膀",
    "Blue Hail Wings": "蓝色冰晶翅膀",
    "Red Devil Wings": "红色恶魔翅膀",
    "Mini Red Devil Wings": "迷你红色恶魔翅膀",
    "Mini Black Devil Wings": "迷你黑色恶魔翅膀",
    "Mini Purple Devil Wings": "迷你紫色恶魔翅膀",
    "From Makai": "来自魔界",
    "From the Other World.": "来自异世界。",
    "From the Future.": "来自未来。",
    "Lux Wings Edition": "Lux翅膀款式",
    "From Heaven.": "来自天界。",
    "From Hell.": "来自地狱。",
    "Small Wings Edition.": "小型翅膀款式。",

    # New monsters, NPCs, maps, and quest labels.
    "Fireball": "火球",
    "Villain Mummy": "反派木乃伊",
    "Fokatuosi": "弗卡托斯",
    "Fighter Kangaroo": "格斗袋鼠",
    "Energy Charger[AP]": "能量充能器[AP]",
    "Weapon Thief": "武器盗贼",
    "Black Makai Cat": "黑色魔界猫",
    "Makai Baralika Ancestral": "魔界巴拉利卡始祖",
    "Makai Poisonous Frog": "魔界毒蛙",
    "Makai Taek Ancestral": "魔界泰克始祖",
    "Makai Wild Plant": "魔界野生植物",
    "Makai Masked Man": "魔界蒙面人",
    "Makai Mira": "魔界米拉",
    "N°3 Tamagami": "3号塔玛伽米",
    "Vegeta SS3": "超级赛亚人3贝吉塔",
    "Goku SS4": "超四悟空",
    "White Namek": "白色那美克",
    "White Namek Transform from DBO Zero.": "来自DBO Zero的白色那美克变身。",
    "A Majin Saibaman Fusion.": "栽培人与魔人的融合形态。",
    "Upa's Temple": "乌帕神殿",
    "Farmer Mone": "农夫莫内",
    "BID6 Makai Realm": "BID6魔界领域",
    "Tamagami": "塔玛伽米",
    "Bardock Makai": "魔界巴达克",
    "Mira Makai": "魔界米拉",
    "[br]It is said that said he was a Dragon Clan.": "[br]据说他曾是那美克龙族。",
    "[br]Defeat the Frieza Army!": "[br]击败弗利萨军团！",
    "Stage 1 Target": "第1阶段目标",
    "Stage 2 Target": "第2阶段目标",
    "To the Hyperbolic Time Chamber": "前往精神时光屋",
    "Makai Shop": "魔界商店",
    "Mushroom Tourist 6": "蘑菇游客6",
    "Ding Keli": "丁克利",
    "Escape": "逃脱",
    "Bulnasaurus": "布尔纳龙",
    "Teacher Tedina": "泰迪娜老师",
    "BID-6 Dungeon Manager": "BID-6副本管理员",
    "Red Pants Army Key": "红裤军钥匙",
}
